# Walrus Site 設定ファイル (Mainnet 本番用)
portal: "walrus.site"

# Walrus-site メインネット用パッケージ ID
package: "0x26eb7ee8688da02c5f671679524e379f0b837a12f1d1d799f255b7eea260ad27"

# 共通設定
general:
    # Sui メインネットの接続先
    rpc_url: "https://fullnode.mainnet.sui.io:443"

    # さっき見つけた「お財布（Walrus設定）」の場所
    walrus_config: "C:/Users/PC USER/.walrus/client_config.yaml"

    # 新しい大工道具（walrusバイナリ）の場所を絶対パスで指定
    walrus_binary: "C:/Users/PC USER/.walrus/walrus.exe"

    # 手数料の上限
    gas_budget: 50000000
